### ISSUE TITLE
PushSharp Apple - The message received was unexpected or badly formatted

### ISSUE THREAD

**Issue by davidreher** [Redth/PushSharp#402]
I am getting the following Error:
System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The message received was unexpected or badly formatted
 --- End of inner exception stack trace ---
at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
at PushSharp.Apple.FeedbackService.Run(ApplePushChannelSettings settings, CancellationToken cancelToken)
at PushSharp.Apple.ApplePushService.<>c__DisplayClass4.<.ctor>b__1(Object state)

The issue occurs with the current version #314 . The the HRESULT error code is -2146233087

**Comment by anuragbhd** [comment]
Hi @davidreher. I am getting the same issue. I see you closed this thread a day after starting it. Were you able to solve it? If so, do you by chance remember what the problem was?

Many thanks!

**Comment by davidreher** [comment]
Hey @anuragbhd,

actually I have switched to [Azure Notfication Hubs](http://azure.microsoft.com/en-us/documentation/services/notification-hubs/). Apple changed it's API for Push Notifications some two or three weeks before I started that issue and PushSharp was not updated yet ...
