### ISSUE TITLE
Exception Info: System.Threading.Tasks.TaskSchedulerException

### ISSUE THREAD

**Issue by ocanal** [Redth/PushSharp#415]
We're trying to push notificiation about 2k device, everytime It crashes after some notification send.
What should be the problem?

```
Application: PushService.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Threading.Tasks.TaskSchedulerException
Stack:
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean)
   at System.Threading.Tasks.Task.InternalStartNew(System.Threading.Tasks.Task, System.Delegate, System.Object, System.Threading.CancellationToken, System.Threading.Tasks.TaskScheduler, System.Threading.Tasks.TaskCreationOptions, System.Threading.Tasks.InternalTaskOptions, System.Threading.StackCrawlMark ByRef)
   at System.Threading.Tasks.TaskFactory.StartNew(System.Action, System.Threading.Tasks.TaskCreationOptions)
   at PushSharp.Core.PushServiceBase+ChannelWorker..ctor(PushSharp.Core.IPushChannel, System.Action`2<PushSharp.Core.IPushChannel,System.Threading.CancellationTokenSource>)
   at PushSharp.Core.PushServiceBase.ScaleChannels(PushSharp.Core.ChannelScaleAction, Int32)
   at PushSharp.Core.PushServiceBase.CheckScale(System.Object)
   at PushSharp.Core.PushServiceBase..ctor(PushSharp.Core.IPushChannelFactory, PushSharp.Core.IPushChannelSettings, PushSharp.Core.IPushServiceSettings)
   at PushSharp.Apple.ApplePushService..ctor(PushSharp.Core.IPushChannelFactory, PushSharp.Apple.ApplePushChannelSettings, PushSharp.Core.IPushServiceSettings)
   at PushService.HandleClientRequest.Gonder(PushService.tb_token, System.String, System.String, System.String)
   at PushService.HandleClientRequest+<>c__DisplayClass4.<ReadCallback>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by andreiholubeu** [comment]
Does anybody resolve this issue?
