### ISSUE TITLE
Any idea about what could cause this exception (APNs)?

### ISSUE THREAD

**Issue by marceln** [Redth/PushSharp#440]
I started getting this error recently, right after I introduced two PushBroker's in my windows service. 

```
System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at Microsoft.Win32.Win32Native.SetEvent(SafeWaitHandle handle)
   at System.Threading.EventWaitHandle.Set()
   at PushSharp.Core.PushServiceBase.<DoChannelWork>c__AnonStorey0.<>m__0(Object sender, SendNotificationResult result)
   at PushSharp.Apple.ApplePushChannel.Cleanup()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

There's nothing unusual about the way I use the brokers. I create notifications, queue them and let PushSharp forward them to APNs. 

The PushServiceSettings for each broker are:

```
            PushServiceSettings pushSettings = new PushServiceSettings
            {
                MaxNotificationRequeues = 0,
                Channels = 2,
                MaxAutoScaleChannels = 200,
                AutoScaleChannels = true
            };
```

Let me know if anyone has any idea about what could lead to this error.

Thanks,
Marcel

**Comment by Webunity** [comment]
Any followup on this? @Redth maybe knows more?

**Comment by tweek82** [comment]
I'm occasionally receiving this error. Log writes this:

```
15:02:09 | PUSHSERVICE | 
Error in Path :
Raw Url :
Message :Safe handle has been closed
Source :mscorlib
Stack Trace :   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at Microsoft.Win32.Win32Native.SetEvent(SafeWaitHandle handle)
   at System.Threading.EventWaitHandle.Set()
   at PushSharp.Core.PushServiceBase.<DoChannelWork>c__AnonStorey0.<>m__0(Object sender, SendNotificationResult result)
   at PushSharp.Android.GcmPushChannel.processResponseOk(GcmAsyncParameters asyncParam)
   at PushSharp.Android.GcmPushChannel.responseCallback(IAsyncResult result)
TargetSite :Void DangerousAddRef(Boolean ByRef)
```

I'm not sure if it's safe to ignore the 'Safe handle has been closed' message. Any suggestions?
