### ISSUE TITLE
Push notifications failing intermittently .

### ISSUE THREAD

**Issue by a3c** [Redth/PushSharp#453]
We have been facing this issue of push notifications failing intermittently for some time now on our development box. 

We are using dev profile (dev p12 file) but push notifications continue to fail randomly giving the error below -

**************
```js

PushSharp.Core.MaxSendAttemptsReachedException: The maximum number of Send attempts to send the notification was reached!

2014-11-11 09:28:07,633 [114] ERROR- Channel Exception: PushSharp.Apple.ApplePushService
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at PushSharp.Apple.FeedbackService.Run(ApplePushChannelSettings settings, CancellationToken cancelToken)
   at PushSharp.Apple.ApplePushService.<>c__DisplayClass4.<.ctor>b__1(Object state)

```
***************

please help.

**Comment by vijayaramb** [comment]
i am also getting this error, kindly help us
