### ISSUE TITLE
PushSharp and Azure

### ISSUE THREAD

**Issue by Discobanan** [Redth/PushSharp#49]
I've been using PushSharp in a .NET 4 WebAPI-application for a while on my local development-machine for sending  push notifications to my iOS app, and it works great. However when i publish it to Azure, the OnChannelException-event is called and i get the exception below. I am using the latest package from NuGet, 1.0.17. Any idea why this happens?

The credentials supplied to the package were not recognized
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface SecModule, String package, CredentialUse intent, SecureCredential scc)
   at System.Net.Security.SecureChannel.AcquireCredentialsHandle(CredentialUse credUsage, SecureCredential& secureCredential)
   at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at PushSharp.Apple.FeedbackService.Run(ApplePushChannelSettings settings, CancellationToken cancelToken)
   at PushSharp.Apple.ApplePushService.<>c__DisplayClass2.<.ctor>b__0(Object state)

**Comment by Tchweizz** [comment]
Hi.
I have some error in pushsharp APN.
The exception stacktrace is:

10/08/2015 11:43:40 : ServiceException - ServiceException Exception: PushSharp.Apple.ApplePushService -> System.ComponentModel.Win32Exception (0x80004005): The credentials supplied to the package were not recognized
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface SecModule, String package, CredentialUse intent, SecureCredential scc)
   at System.Net.Security.SecureChannel.AcquireCredentialsHandle(CredentialUse credUsage, SecureCredential& secureCredential)
   at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at PushSharp.Apple.FeedbackService.Run(ApplePushChannelSettings settings, CancellationToken cancelToken)
   at PushSharp.Apple.ApplePushService.<>c__DisplayClass4.<.ctor>b__1(Object state)


Need help.
Thanks

**Comment by GeoffArmstrong** [comment]
I'm also experiencing this "The credentials supplied to the package were not recognized" issue.

My configuration: I'm using Azure Web Apps (née Azure Websites), and I'm using Pushsharp in a Azure Webjob (a c# console app).  My .p12 file is compiled as a "embedded resource".  The odd thing is that this issue seems to be really periodic.  When my c# console app starts up (in the webjob), it logs the name of the certificate that it's using, and it logs the password for that certificate, and it logs which APNS environment (production/sandbox) is being used.

I'm running on a "Medium" (2 processor) instance, and I have two deployment slots.  A production and staging deployment slot.  Sometimes both slots are throwing the "The credentials supplied to the package were not recognized" error, sometimes just one of them are, sometimes neither of them are.  Just now there is one slot that is giving the error, irrespective of whether that slot is the production or staging instance.  And looking at the debug logs, both deployment slots are using the same APNS settings (production, same .p12 file, same password).

So, this is rather frustrating to say the least.

**Comment by siroky** [comment]
Happens to us too (large standard website, multiple instances, multiple regions). After restart, it sometimes goes away, sometimes it starts happening periodically every ten minutes. So I guess it kind of depends on the machine the web app instance is deployed to. I've opened a support ticket and will post updates here if anything interesting comes out of it...

**Comment by GeoffArmstrong** [comment]
@siroky I hope you are able to find (and share) a solution!

As a alternate technical solution, I'm considering running these jobs on a different non-Azure VM/service - it's just unfortunate since this is what Webjobs is supposed enable!

**Comment by vsporrior** [comment]
Also having this issue on a webjob. Things seemed to be working fine until I had to regenerate my APNS cert, as the current one was expiring. Now I get this issue periodically. Running locally seems fine. Any ideas anyone?

**Comment by siroky** [comment]
Hi, sorry that I forgot to post the solution here. In our case, we had the certificate as an embedded resource of the project. We changed it according to this guide: https://azure.microsoft.com/en-us/blog/using-certificates-in-azure-websites-applications/ which resolved the issue in our case.
