### ISSUE TITLE
Failure: PushSharp.Apple.ApplePushService -> Exception of type 'PushSharp.Apple.NotificationFailureException' was thrown

### ISSUE THREAD

**Issue by avmgan** [Redth/PushSharp#510]
Hi Redth,

I am using PushSharp in my application for sending push notification. It's working fine for android.

For apple iOS - it's not working, we are using development certificate file with password.
Initially we have used wrong password then later we found that issue and corrected.

It's getting bellow error message

Channel Created for: PushSharp.Apple.ApplePushService Failure: PushSharp.Apple.ApplePushService -> Exception of type 'PushSharp.Apple.
NotificationFailureException' was thrown. -> {"aps":{"alert":"Hello World!","badge":7,"sound":"default"}}

Error status code:8
Error Description: Invalid token

App developed by one of our vendor and push notification we are doing from our side.
vendor sending push notification using some PHP code it's working.

I have installed that app on my iPhone's device and they send test push notification it's working fine.

But i was try to send using Pushsharp framework it's not working.

They saying development certificate file is correct it's working fine.

I have tried all possible option from my end but i am not getting any clue why its behaving odd with development certificate .p12. Please help me out to resolve this issue.

Will wait for your reply.

Thanks,
Velu

**Comment by avmgan** [comment]
Code that we used for development:

            var push = new PushBroker();
            var appleCert = File.ReadAllBytes(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "xxxxPass.p12"));
            push.RegisterAppleService(new ApplePushChannelSettings(appleCert, "xxxx12345")); //Extension method
            push.QueueNotification(new AppleNotification()
                                       .ForDeviceToken("a51b4e80d12df0946d10413991ce1f7ab57c05bab8a292fc703ded34ce77b91f")
                                       .WithAlert("Hello World!")
                                       .WithSound("default")
                                       .WithBadge(7));

Thanks,
Velu

**Comment by craigaustin** [comment]
I have the same problem.

**Comment by jainik87** [comment]
I have also same problem.

**Comment by jainik87** [comment]
Please resolve this issue asap.

**Comment by mevadakrunal** [comment]
Hello Everyone,

Please help me,

I have same issue as per above post. 

I used below code for send notification to IOS device:

            var appleCert = File.ReadAllBytes(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "../../../Resources/xxxxxxxxx-2015.p12"));

            push.RegisterAppleService(new ApplePushChannelSettings(appleCert, "xxxxxxxx"));

	    push.QueueNotification(new AppleNotification()
 .ForDeviceToken("17281e86cf1fc7b3f88c75873a53a4809145cc58080d4eed752d6ee097d34094")
			                           .WithAlert("Hello World!")
			                           .WithBadge(7)
			                           .WithSound("sound.caf"));

then i got below error

Failure: PushSharp.Apple.ApplePushService -> Exception of type 'PushSharp.Apple.NotificationFailureException' was thrown

I had work in pass with same thing at that time it's work like pretty but now it's give me error as above.

Please give some solution of this issue ASAP. 

Thanks,
Krunal

**Comment by Fleskarn** [comment]
Have same problem, except I dont see the error code (do you find it somewhere by debugging?)

This is what my log outputs

Channel Created for: PushSharp.Apple.ApplePushService
'PushNotificationServer.vshost.exe' (Managed (v4.0.30319)): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll', Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PushNotificationServer.vshost.exe' (Managed (v4.0.30319)): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll', Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
A first chance exception of type 'System.IO.IOException' occurred in System.dll
A first chance exception of type 'System.ObjectDisposedException' occurred in System.dll
A first chance exception of type 'System.IO.IOException' occurred in System.dll
A first chance exception of type 'System.ObjectDisposedException' occurred in System.dll
A first chance exception of type 'System.IO.IOException' occurred in System.dll
A first chance exception of type 'System.ObjectDisposedException' occurred in System.dll
A first chance exception of type 'System.IO.IOException' occurred in System.dll
A first chance exception of type 'System.ObjectDisposedException' occurred in System.dll
A first chance exception of type 'System.IO.IOException' occurred in System.dll
A first chance exception of type 'System.ObjectDisposedException' occurred in System.dll
A first chance exception of type 'System.IO.IOException' occurred in System.dll
A first chance exception of type 'System.ObjectDisposedException' occurred in System.dll
A first chance exception of type 'System.IO.IOException' occurred in System.dll
A first chance exception of type 'System.ObjectDisposedException' occurred in System.dll
A first chance exception of type 'System.IO.IOException' occurred in System.dll
A first chance exception of type 'System.ObjectDisposedException' occurred in System.dll
A first chance exception of type 'System.IO.IOException' occurred in System.dll
Service Exception: PushSharp.Apple.ApplePushService -> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at PushSharp.Apple.FeedbackService.Run(ApplePushChannelSettings settings, CancellationToken cancelToken) in c:\Users\WestberghA\Google Drive\Projects\PushSharp-master\PushSharp.Apple\FeedbackService.cs:line 66
   at PushSharp.Apple.ApplePushService.<>c__DisplayClass4.<.ctor>b__1(Object A first chance exception of type 'System.IO.IOException' occurred in System.dll
A first chance exception of type 'System.ObjectDisposedException' occurred in System.dll
state) in c:\Users\WestberghA\Google Drive\Projects\PushSharp-master\PushSharp.Apple\ApplePushService.cs:line 51
A first chance exception of type 'System.IO.IOException' occurred in System.dll
Failure: PushSharp.Apple.ApplePushService -> The maximum number of Send attempts to send the notification was reached! -> {"aps":{"alert":"hej fisk","badge":1,"sound":"sound.caf"}}

**Comment by mattio** [comment]
@avmgan The error you provided in your original post has an "Invalid token" message. It looks like that can happen in the AppleNotification.cs class if the device token is invalid on [line 125](https://github.com/Redth/PushSharp/blob/master/PushSharp.Apple/AppleNotification.cs#L125) and on [line 131](https://github.com/Redth/PushSharp/blob/master/PushSharp.Apple/AppleNotification.cs#L131).

Can you generate that device token again to make sure it is correct?
