### ISSUE TITLE
PushSharp and Apple APNS connectivity problem.

### ISSUE THREAD

**Issue by zaidi1** [Redth/PushSharp#527]
It was working perfeclty, but today its giving following error.

ServiceException : System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at PushSharp.Apple.FeedbackService.Run(ApplePushChannelSettings settings, CancellationToken cancelToken) in c:\Projects\Push Notifications\PushSharp-master\PushSharp.Apple\FeedbackService.cs:line 66
   at PushSharp.Apple.ApplePushService.<>c__DisplayClass4.<.ctor>b__1(Object state) in c:\Projects\Push Notifications\PushSharp-master\PushSharp.Apple\ApplePushService.cs:line 51

My code 
     push = new PushBroker();
            //Wire up the events for all the services that the broker registers
            push.OnNotificationSent += NotificationSent;
            push.OnChannelException += ChannelException;
            push.OnServiceException += ServiceException;
            push.OnNotificationFailed += NotificationFailed;
            push.OnDeviceSubscriptionExpired += DeviceSubscriptionExpired;
            push.OnDeviceSubscriptionChanged += DeviceSubscriptionChanged;
            push.OnChannelCreated += ChannelCreated;
            push.OnChannelDestroyed += ChannelDestroyed;

            string path = MyDirectory() + @"\pushNotifcation_Dev.p12";
         
            if (File.Exists(path))
            {
                push.RegisterAppleService(new PushSharp.Apple.ApplePushChannelSettings(false, path, "pwd", false));
            }
             }

**Comment by ilyabreev** [comment]
It looks like machine executing this code does not have certificate with private key installed in local certification storage. Can you verify that your certificate storage has `pushNotifcation_Dev.p12` with private key installed?

**Comment by zaidi1** [comment]
Yes, it has everything and it worked for 2 days perfectly as I mentioned already.
Anyhow, I again generate a new certificate and now its working, but I am not sure for how many days it will work. And if this happened to my online application then what should I say to my client?

**Comment by ilyabreev** [comment]
Maybe some of your actions on apple developer portal took effect? Did you delete/regenerate your provisioning profile or app settings on developer portal?

**Comment by pauldambra** [comment]
I'm having this exact error whether or not the certificate is installed (and since in this case it is being read from a file that shouldn't matter)

I also have a ruby script using [Houston](https://github.com/nomad/houston) that can send a push notification on the same machine with the same certificate.

So:
I have ports 2195 and 2196 open.
I have verified the certificate is valid
I have verified that certificate can push an alert to that device

What else can be done to investigate?

**Comment by pauldambra** [comment]
I just found [this stackoverflow question](http://stackoverflow.com/questions/23329040/pushsharp-apns-production-the-credentials-supplied-to-the-package-were-not-reco) where the accepted answer says to export only the private key and not the certificate.

Doing so meant I could send push notifications with push sharp.

Is that expected? If so I'll update the wiki page on how to export a certificate for APNS to make it clear.
