### ISSUE TITLE
Apple certificate - The crendentials supplied to the package were not recognized

### ISSUE THREAD

**Issue by tiwari-abhishek** [Redth/PushSharp#645]
### What version of PushSharp are you using?
v2
### Describe your issue:
A .p12 file containing the certificate and private key throws this error on calling
stream.AuthenticateAsClient(this.appleSettings.Host, this.certificates, System.Security.Authentication.SslProtocols.Tls, false);

The same certificate when used through a PHP program directly communicating with APNS is able to send notifications. My customer doesnt want to regenerate a certificate because he says the certificate is valid as proved by testing it with APNS with another tool on the same machine

I have found few links on the internet where people dropped the certificate part from the p12 and only stored the private key in the .p12 file. This seems to be a working solution as per many developers.
http://stackoverflow.com/questions/23329040/pushsharp-apns-production-the-credentials-supplied-to-the-package-were-not-reco

I wanted to understand if this is really how it is supposed to work? If yes, I would force the customer to get a new .p12 without the certificate, and only embed the private key in it. 

If not, and if a .p12 can and should have both the certificate and the private key in it, then what exactly am I doing wrong?

### What are the steps required to reproduce this issue?
.p12 file with a certificate and a private key
### Please provide any Exception Stack Traces
System.ComponentModel.Win32Exception (0x80004005): The credentials supplied to the package were not recognized
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface SecModule, String package, CredentialUse intent, SecureCredential scc)
   at System.Net.Security.SecureChannel.AcquireCredentialsHandle(CredentialUse credUsage, SecureCredential& secureCredential)
   at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at PushSharp.Apple.FeedbackService.Run(ApplePushChannelSettings settings, CancellationToken cancelToken) in \PushSharp.Apple\FeedbackService.cs:line 65
   at PushSharp.Apple.ApplePushService.<>c__DisplayClass3_0.<.ctor>b__0(Object state) in \PushSharp.Apple\ApplePushService.cs:line 31

**Comment by jasonli826** [comment]
I am also encountering this issue. i have spent serveral days to solve it however still unable to fix it. wish anyone can tell me the solution. Thanks

**Comment by Redth** [comment]
In my experience, I've had to always only select the private key portion of the cert in Keychain and export from the private key only.  Not sure why exactly this works how it does, but that's what has to happen.

**Comment by cory-colt** [comment]
I'm still getting this same issue. Works great locally, but I upload the same files and cert to the web server and I get the same error. "The credentials supplied to the package were not recognized." Is there any solution to this?

**Comment by netwang** [comment]
I had the same issue in .Net Framework 4.8 web site. In the app pool in IIS manager, in Advanced Setting, set 'Identity' to 'LocalSystem' to fix it.

I had the same Apple push in a Windows Service. It worked without any issue
