### ISSUE TITLE
XML exception is throwing when trying to send push messages to BlackBerry

### ISSUE THREAD

**Issue by silverhawk1086** [Redth/PushSharp#676]
I am using the latest version of PushSharp.

When I try to send push messages to BlackBerry, I am getting an XML exception. The exception is below:

```
System.Xml.XmlException: The 'HR' start tag on line 1 position 1071 does not match the end tag of 'body'. Line 1, position 1132.
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
   at PushSharp.Blackberry.BlackberryPushChannel.SendNotification(INotification notification, SendNotificationCallbackDelegate callback)
```

My code is as below.

```
private void SendNotificationViaBlackBerry(Notification notification, string notificationContent, string pushToken, int notificationCount)
       {
           PushSharp.Blackberry.BlackberryPushChannelSettings settings = new PushSharp.Blackberry.BlackberryPushChannelSettings("<app_id>", "<password>");
           push.RegisterBlackberryService(settings, "<app_id>");
           PushSharp.Blackberry.BlackberryNotification bNotification = new PushSharp.Blackberry.BlackberryNotification();
           bNotification.PpgNotifyRequestedTo = "https://cp1359.pushapi.na.blackberry.com";
           PushSharp.Blackberry.BlackberryRecipient recispent = new PushSharp.Blackberry.BlackberryRecipient(pushToken);
           recispent.Port = <port>;

           bNotification.SourceReference = "<app_id>";
           bNotification.Recipients = new List<PushSharp.Blackberry.BlackberryRecipient>() { recispent };
           bNotification.Content = new PushSharp.Blackberry.BlackberryMessageContent(notificationContent);
           push.QueueNotification(bNotification);
       }
```

Kindly let me know how this can be fixed.

**Comment by Redth** [comment]
My guess is you have some malformed XML in your `BlackberryMessageContent`

**Comment by silverhawk1086** [comment]
Is it possible for you to send a sample code on how to implement BB push notification using PushSharp?

**Comment by Redth** [comment]
Sorry but I don't have any way to test on blackberry.

You're going to have to try and do this alone :(

Only thing I can say is someone in the past has used this code successfully!

**Comment by silverhawk1086** [comment]
Is there a documentation or sample code for this in BlackBerry?
