### ISSUE TITLE
There were not enough free threads in the ThreadPool to complete the operation.

### ISSUE THREAD

**Issue by igorfedulaev** [Redth/PushSharp#704]
### What version of PushSharp are you using?

I am using PushSharp 4.0.10. Download  13.05.2016

### Describe your issue:

I has one mistake.

System.InvalidOperationException: There were not enough free threads in the ThreadPool to complete the operation.

### What are the steps required to reproduce this issue?

My task. I has three platform for push notification: Android, iOS, Windows Phone. In test I had 107 tokens for different platform (49 live tokens (more part Android and Windows Phone) and other died tokens), and only one broker for each platform. First execute push notifications send only 1/3 push notifications, other with error. After second execute, send other notifications 2/3. And at last execute, other push which finished early with errors was finished

### Please provide any Exception Stack Traces

First for Android.

Android. Notification Failed for some (Unknown Reason) System.InvalidOperationException: There were not enough free threads in the ThreadPool to complete the operation.
   at System.Net.HttpWebRequest.BeginGetRequestStream(AsyncCallback callback, Object state)
   at System.Net.Http.HttpClientHandler.StartGettingRequestStream(RequestState state)
   at System.Net.Http.HttpClientHandler.PrepareAndStartContentUpload(RequestState state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PushSharp.Google.GcmServiceConnection.<Send>d__6.MoveNext()

Second for Windows Phone

Windows Phone. Notification Failed for some (Unknown Reason) System.InvalidOperationException: There were not enough free threads in the ThreadPool to complete the operation.
   at System.Net.HttpWebRequest.BeginGetRequestStream(AsyncCallback callback, Object state)
   at System.Net.Http.HttpClientHandler.StartGettingRequestStream(RequestState state)
   at System.Net.Http.HttpClientHandler.PrepareAndStartContentUpload(RequestState state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PushSharp.Windows.WnsServiceConnection.<Send>d__9.MoveNext()

Sorry for my terrible English)

**Comment by igorfedulaev** [comment]
Sorry. Resolved problem
Set into ThreadPool max and min length of threads

**Comment by thyams** [comment]
I believe there is an infinite await async loop inside the PushSharp.Core.WorkerService.

The following stack trace, is from an w3wp.exe - application dump, one that has over 6,000 threads in 24 hours.
```
000000b7250fe120 00007ff8214285f6 (MethodDesc 00007ff81e226910 +0x106 System.Threading.CancellationToken.Register(System.Action`1<System.Object>, System.Object, Boolean, Boolean)), calling (MethodDesc 00007ff81e2266c0 +0 System.Threading.CancellationTokenSource.InternalRegister(System.Action`1<System.Object>, System.Object, System.Threading.SynchronizationContext, System.Threading.ExecutionContext))
000000b7250fe130 00007ff821404b72 (MethodDesc 00007ff81e223de8 +0x42 System.Threading.Tasks.Task.TaskConstructorCore(System.Object, System.Object, System.Threading.CancellationToken, System.Threading.Tasks.TaskCreationOptions, System.Threading.Tasks.InternalTaskOptions, System.Threading.Tasks.TaskScheduler)), calling clr!JIT_WriteBarrier
000000b7250fe140 00007ff81e097ac7 (MethodDesc 00007ff81e1fc628 +0x17 System.Threading.PlatformHelper.get_ProcessorCount()), calling clr!JIT_GetSharedNonGCStaticBaseNoCtor_InlineGetAppDomain
000000b7250fe158 00007ff87d72541b clr!ObjectNative::WaitTimeout+0x7b, calling clr!LazyMachStateCaptureState
000000b7250fe1a0 00007ff8219ed59a (MethodDesc 00007ff820cdaa30 +0x7a System.Threading.SemaphoreSlim.WaitUntilCountOrTimeout(Int32, UInt32, System.Threading.CancellationToken)), calling (MethodDesc 00007ff81e0c88e0 +0 System.Threading.Monitor.Wait(System.Object, Int32, Boolean))
000000b7250fe1f0 00007ff8219ecfcb (MethodDesc 00007ff820cdaa20 +0x15b System.Threading.SemaphoreSlim.Wait(Int32, System.Threading.CancellationToken)), calling (MethodDesc 00007ff820cdaa30 +0 System.Threading.SemaphoreSlim.WaitUntilCountOrTimeout(Int32, UInt32, System.Threading.CancellationToken))
000000b7250fe200 00007ff8214192df (MethodDesc 00007ff81e224748 +0x14f System.Threading.Tasks.Task.ContinueWithCore(System.Threading.Tasks.Task, System.Threading.Tasks.TaskScheduler, System.Threading.CancellationToken, System.Threading.Tasks.TaskContinuationOptions)), calling (MethodDesc 00007ff81e224788 +0 System.Threading.Tasks.Task.AddTaskContinuation(System.Object, Boolean))
000000b7250fe280 00007ff8219ecb4d (MethodDesc 00007ff821ce3ad8 +0x10d System.Collections.Concurrent.BlockingCollection`1[[System.__Canon, mscorlib]].TryTakeWithNoTimeValidation(System.__Canon ByRef, Int32, System.Threading.CancellationToken, System.Threading.CancellationTokenSource)), calling (MethodDesc 00007ff820cdaa20 +0 System.Threading.SemaphoreSlim.Wait(Int32, System.Threading.CancellationToken))
000000b7250fe2f0 00007ff8219ebcbc (MethodDesc 00007ff821ce6628 +0xcc System.Collections.Concurrent.BlockingCollection`1+<GetConsumingEnumerable>d__68[[System.__Canon, mscorlib]].MoveNext()), calling (MethodDesc 00007ff821ce3ad8 +0 System.Collections.Concurrent.BlockingCollection`1[[System.__Canon, mscorlib]].TryTakeWithNoTimeValidation(System.__Canon ByRef, Int32, System.Threading.CancellationToken, System.Threading.CancellationTokenSource))
000000b7250fe340 00007ff8218c3d4a (MethodDesc 00007ff821cfa2e0 +0x21a PushSharp.Core.ServiceWorker`1+<<Start>b__17_0>d[[System.__Canon, mscorlib]].MoveNext())
000000b7250fe3f0 00007ff8218c36ae (MethodDesc 00007ff821cfa670 +0xae System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[PushSharp.Core.ServiceWorker`1+<<Start>b__17_0>d[[System.__Canon, mscorlib]], PushSharp.Core]](<<Start>b__17_0>d<System.__Canon> ByRef))
000000b7250fe4b0 00007ff8218c35ce (MethodDesc 00007ff821cf7648 +0xae PushSharp.Core.ServiceWorker`1[[System.__Canon, mscorlib]].<Start>b__17_0()), calling (MethodDesc 00007ff821cfa670 +0 System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[PushSharp.Core.ServiceWorker`1+<<Start>b__17_0>d[[System.__Canon, mscorlib]], PushSharp.Core]](<<Start>b__17_0>d<System.__Canon> ByRef))
000000b7250fe4c0 00007ff81e55ec59 (MethodDesc 00007ff81e0e4c40 +0x9 System.Threading.HostExecutionContextManager.GetCurrentHostExecutionContextManager()), calling (MethodDesc 00007ff81e0e3d70 +0 System.AppDomainManager.get_CurrentAppDomainManager())
000000b7250fe560 00007ff8219eb535 (MethodDesc 00007ff81e225638 +0x55 System.Threading.Tasks.Task`1[[System.__Canon, mscorlib]].InnerInvoke())
000000b7250fe5c0 00007ff82141b78a (MethodDesc 00007ff81e2242a0 +0x4a System.Threading.Tasks.Task.Execute())
000000b7250fe5d0 00007ff82141b716 (MethodDesc 00007ff81e224350 +0x16 System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)), calling clr!JIT_IsInstanceOfClass
000000b7250fe600 00007ff81e55f639 (MethodDesc 00007ff81e2c4ba0 +0x169 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean))
000000b7250fe610 00007ff87d7360ed clr!JIT_GetGCThreadStaticBase_Helper+0x135, calling clr!HelperMethodFrameRestoreState
000000b7250fe6d0 00007ff81e55e827 (MethodDesc 00007ff81e2c4b90 +0x17 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)), calling (MethodDesc 00007ff81e2c4ba0 +0 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean))
000000b7250fe700 00007ff82141b4bd (MethodDesc 00007ff81e224340 +0x22d System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)), calling (MethodDesc 00007ff81e2c4b90 +0 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean))
000000b7250fe710 00007ff81fbc9f32 (MethodDesc 00007ff81e2c4bd0 +0x1e2 System.Threading.ExecutionContext.SetExecutionContext(System.Threading.ExecutionContext, Boolean)), calling clr!JIT_ByRefWriteBarrier
000000b7250fe7b0 00007ff82141b20f (MethodDesc 00007ff81e224330 +0xaf System.Threading.Tasks.Task.ExecuteEntry(Boolean)), calling (MethodDesc 00007ff81e224340 +0 System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef))
000000b7250fe7f0 00007ff81e55f639 (MethodDesc 00007ff81e2c4ba0 +0x169 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean))
000000b7250fe8c0 00007ff81e55e827 (MethodDesc 00007ff81e2c4b90 +0x17 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)), calling (MethodDesc 00007ff81e2c4ba0 +0 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean))
000000b7250fe8d0 00007ff88fec6afd ntdll!LdrpLoadDll+0x111, calling ntdll!_security_check_cookie
000000b7250fe8f0 00007ff82012ce3d (MethodDesc 00007ff81e2c4b80 +0x4d System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)), calling (MethodDesc 00007ff81e2c4b90 +0 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean))
000000b7250fe910 00007ff82012ccf6 (MethodDesc 00007ff81e2c5130 +0x36 System.Runtime.Remoting.Messaging.LogicalCallContext.get_SecurityData()), calling clr!JIT_WriteBarrier
000000b7250fe940 00007ff8214150e0 (MethodDesc 00007ff8203d6518 +0x60 System.Threading.ThreadHelper.ThreadStart(System.Object)), calling (MethodDesc 00007ff81e2c4b80 +0 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object))
000000b7250fe950 00007ff87d5d5512 clr!SigPointer::PeekElemTypeNormalized+0x32, calling clr!SigPointer::PeekElemTypeClosed
```

Each of these tasks never truly finishes so they consume threads not stop.
