### ISSUE TITLE
Apns notification error: 'ConnectionError' 

### ISSUE THREAD

**Issue by cDoru** [Redth/PushSharp#706]
### What version of PushSharp are you using?

We are using PushSharp 4.0.10

### Describe your issue:

We are currently using PushSharp in an Azure Worker Role (processing pns from a database table). There is no parallel processing (meaning there is a single ApnsServiceBroker instance running continuously). Every once in a while we get a "Failed to Connect, check your firewall settings!" error. I would say 50% of the push notifications work and the other 50% fail with this message.

Do you have any idea why this happens ? 
Thank you

### What are the steps required to reproduce this issue?

Run PushSharp as a service inside an Azure Worker Role project, or an Azure Web Role project. 

### Please provide any Exception Stack Traces

One or more errors occurred.

Apns notification error: 'ConnectionError'
   at PushSharp.Apple.ApnsServiceConnection.<Send>d__2.MoveNext()
Failed to Connect, check your firewall settings!
   at PushSharp.Apple.ApnsConnection.<connect>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PushSharp.Apple.ApnsConnection.<SendBatch>d__21.MoveNext()
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 17.110.226.164:2195
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PushSharp.Apple.ApnsConnection.<connect>d__25.MoveNext()

**Comment by SamVanCutsem** [comment]
Any updates on this? I'm getting the same error

**Comment by cDoru** [comment]
No. Unfortunately for us we had a release scheduled soon so we decided to go with azure notification hub

**Comment by SamVanCutsem** [comment]
Our firewall blocked the outgoing packages to the APNS service. We had to open all connections to 17.0.0.0/8 (Apple owns all those IP adresses) to make it work.

**Comment by idoadse** [comment]
Hi, having the same issue in Azure platform (basic plan).
Its happening often but not all the time. Sam, was it also happening in your case? maybe only some port/ips are blocked? is it possible that it is related to some errors in sending (e.g timeout because of bad device token)

**Comment by darthgogy** [comment]
I have the same problem. Sometimes I get this exception after some timeout.
InternalBatchFailureRetryCount do not work with exeptions in connect() method. It's a pity.
> How many times the internal batch will retry to send in case of network failure. The default value is 1.
So System.Net.Sockets.SocketException is a network failure too.

**Comment by gemsuraj** [comment]
I'm too getting the same error. In start of few days it worked flawless. But suddenly it started showing connection error. I've deployed the same to another server and it worked. Tried switching the azure plan from basic to premium but sill no luck on azure. I guess azure is trying us forcefully use their notification hub.

**Comment by darthgogy** [comment]
I've managed to send native APNs pushes via Azure Notification Hub without any additional implementation in iOS app. I think it's a good alternative for now. What can I say about PushSharp? It's good if you need stand alone solution. If you use Azure you should use Notification Hub. It can send native pushes.

**Comment by AdrianBarreraLopez** [comment]
try remove blank spaces and '<' '>'< the token device

**Comment by arokiamanojkumar1** [comment]
I face the same issue.  Does anyone have a concreconcrete solution? anything has to be done in firewall rules? Thanks

**Comment by idanbezalel** [comment]
I face same issue , im deleting and republishing the certificate and it works for two hours and than fails (connection error ) on azure web app.
on my dev machine it always works ...

**Comment by mitpoo** [comment]
You can resolve this issue by adding a line <trust level="Full"/> in your web.config file. But problem remain same if you host your website on shared hosting.

**Comment by mnaoumov** [comment]
@mitpoo which line are you referering to?

**Comment by filip76w** [comment]
I have the same problem. The problem of connection arose a few weeks ago, it worked fine before.
Is there any solution to this?

**Comment by mitpoo** [comment]
That issue is due to server trust level security. I have used PHP
pushnotification code and called that function from .net application using
Web Request.

Let me know if you have any query for same.

Thank you,
Pooja Doshi

**Comment by filip76w** [comment]
I send notifications directly from an asp.net website. 
What do you mean by "adding a line in your web.config" in your previous answer?

**Comment by mitpoo** [comment]
I have added that line in web.config that works fine for few days on server
but again same issue arose. I am sorry, i forgot to update my comment. But
if you are using shared hosting then you will sure face trust level issue
for sending pushnotification using .net application.

Thanks
Pooja Doshi

**Comment by darthgogy** [comment]
Problem is in ApnsConnection.cs (line 143). We have try-finally block there. Configuration.InternalBatchFailureRetryCount useless in this situation because there is no catch there. So if "await connect ()" fails it will not retry to connect. You can clone PushSharp git and fix it by yourself. https://github.com/Redth/PushSharp/blob/5abac610539174a772fc0907403ddbf042c66856/PushSharp.Apple/ApnsConnection.cs#L143

**Comment by mitpoo** [comment]
Ok..  will try and update you soon.. Thank you

**Comment by mitpoo** [comment]
Will it work if i use new code from git and integrate same in my .net
application and publish same and upload on Godaddy server on medium trust
level? As when i am calling APNSConfiguration function it throws an error
of security permission which is not yet resolve, i guess.

Let me know for same..
Thank you

**Comment by mitpoo** [comment]
Hi,

Still this pushsharp code is again filed to run on medium trust level in
Godaddy shared hosting. So, Issue is still not resolved for secure APNS
configuration class. May be you did not get what is my actual issue is. I
am facing security permission issue while creating APNS configuration on
medium trust using asp.net application. So, Pushsharp is not that much
helpful if you are working with shared hosting.


Thanks,
Pooja Doshi

**Comment by bidianqing** [comment]
IIS Express is Succeeded and IIS is Failed

**Comment by yen-ssu** [comment]
I think this is APNS problem. I try to test connection to sandbox server using Powershell. It sometimes succeeds, sometimes fails. I recommend to test apns push with production server

Sample command:
Test-NetConnection -ComputerName gateway.sandbox.push.apple.com -Port 2195
Test-NetConnection -ComputerName feedback.sandbox.push.apple.com -Port 2196
Test-NetConnection -ComputerName gateway.push.apple.com -Port 2195
Test-NetConnection -ComputerName feedback.sandbox.push.apple.com -Port 2196

**Comment by yen-ssu** [comment]
@bidianqing how you fixed your problem?

**Comment by bidianqing** [comment]
@yen-ssu 
![image](https://user-images.githubusercontent.com/12196280/27574047-4e35295e-5b47-11e7-808d-7ab69dbdd70b.png)
![image](https://user-images.githubusercontent.com/12196280/27574051-539cea6c-5b47-11e7-8e4a-8dbc7cda871b.png)
![image](https://user-images.githubusercontent.com/12196280/27574056-57ab7b96-5b47-11e7-9040-56dae223b439.png)

**Comment by sercanparker** [comment]
@SamVanCutsem I am facing same issue for API project hosted on Azure App Service. I could not find any firewall settings for App Service, could you describe firewall settings on portal ?

**Comment by sercanparker** [comment]
@bidianqing Could you give any screenshots in English ?

**Comment by bidianqing** [comment]
@sercanparker 
Find the corresponding application pool,Right click,view Advanced Settings,
Process model→
![image](https://user-images.githubusercontent.com/12196280/28203605-074aacb2-68ad-11e7-98e3-97dce0d016c2.png)
custom account

**Comment by rammi44** [comment]
I am facing the same issue.. Our application is hosted on  everleap.

**Comment by fatim** [comment]
Same issue on Azure WebApp.
