### ISSUE TITLE
ios - if one DeviceToken are wrong no push are sent

### ISSUE THREAD

**Issue by jsundstr** [Redth/PushSharp#713]
v.4.0.10.0

Problem
If I send a batch of notifications and one of the DeviceToken are wrong the correct ones dont sends,

Try it
send a batch with two DeviceToken one wrong and one correct, and you dont get the correct pushnotification either

Exception
2016-05-31 17:18:14. [DEBUG] Scaled Changed to: 1
2016-05-31 17:18:14. [INFO] Stopping: Waiting on Tasks
2016-05-31 17:18:14. [INFO] Waiting on all tasks 2
2016-05-31 17:18:15. [INFO] APNS-Client[1]: Sending Batch ID=1, Count=2
2016-05-31 17:18:15. [ERROR] APNS-CLIENT[1]: Send Batch Error: Batch ID=1, Error=PushSharp.Core.NotificationException: Invalid DeviceToken
   at PushSharp.Apple.ApnsNotification.ToBytes()
   at PushSharp.Apple.ApnsConnection.createBatch(List`1 toSend)
   at PushSharp.Apple.ApnsConnection.<SendBatch>d__21.MoveNext()
2016-05-31 17:18:15. [INFO] APNS-Client[1]: Sent Batch, waiting for possible response...
2016-05-31 17:18:15. [ERROR] APNS-Client[1]: Reader Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PushSharp.Apple.ApnsConnection.<Reader>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PushSharp.Apple.ApnsConnection.<SendBatch>d__21.MoveNext()
2016-05-31 17:18:15. [INFO] APNS-Client[1]: Done Reading for Batch ID=1, reseting batch timer...
Apple Notification Failed: ID=1, Code=ConnectionError
Apple Notification Failed: ID=2, Code=ConnectionError
2016-05-31 17:18:15. [INFO] All Tasks Finished
2016-05-31 17:18:15. [INFO] Passed WhenAll
2016-05-31 17:18:15. [INFO] Broker IsCompleted
2016-05-31 17:18:15. [DEBUG] Broker Task Ended
2016-05-31 17:18:15. [INFO] Stopping: Done Waiting on Tasks

Code
                    // Wire up events
                    apnsBroker.OnNotificationFailed += (notification, aggregateEx) =>
                        {
                            string error = string.Empty;
                            aggregateEx.Handle(ex =>
                            {

                                //See what kind of exception it was to further diagnose
                                if (ex is ApnsNotificationException)
                                {
                                    var notificationException = (ApnsNotificationException)ex;

                                    //Deal with the failed notification
                                    var apnsNotification = notificationException.Notification;
                                    var statusCode = notificationException.ErrorStatusCode;
                                    
                                    error = $"Apple Notification Failed: ID={apnsNotification.Identifier}, Code={statusCode}";
                                    upd_failed(notification, error);
                                    Console.WriteLine(error);

                                }
                                else
                                {
                                    //Inner exception might hold more useful information like an ApnsConnectionException 
                                    error = $"Apple Notification Failed for some unknown reason : {ex.InnerException}";
                                    upd_failed(notification, error);
                                    Console.WriteLine(error);
                                }
                                
                                // Mark it as handled
                                return true;
                            });
                        };
                        apnsBroker.OnNotificationSucceeded += (notification) =>
                        {
                            Console.WriteLine("Apple Notification Sent!");
                            upd_sent(notification);
                        };

                        // Start the broker
                        apnsBroker.Start();

                    foreach (XmlNode node_ios in list_ios)
                    {
                        
                            string device_token = node_ios.Attributes.GetNamedItem("device_token").Value;
                            string json = jsonAPNS(node_ios);

                            apnsBroker.QueueNotification(new ApnsNotification
                            {
                                DeviceToken = device_token,
                                Payload = JObject.Parse(json)
                            });

                    }
                        // Stop the broker, wait for it to finish   
                        // This isn't done after every message, but after you're
                        // done with the broker
                        apnsBroker.Stop();

**Comment by bernik1980** [comment]
Can confirm that, did cost me some time some days ago.

Sending one push after another now until this is fixed.

**Comment by jsundstr** [comment]
Same for me sending  one push at time, very time consuming...

**Comment by Obvious1992** [comment]
Same problem here.

**Comment by rid00z** [comment]
How do you send one at time rather than using the queue?

**Comment by jsundstr** [comment]
I,m on vaccation. Back on July 11th


Regards,
Johan Sundström

**Comment by Obvious1992** [comment]
I can't access my code at the moment. But I think there was a method SetScale to send one at time.

**Comment by bernik1980** [comment]
Any news on this? Its really a show-stopper. Sending 150 notifications to iOS devices will take minutes sending one after another.

**Comment by wmlai29** [comment]
Any news on this?
(>"<) Same problem here.

**Comment by sasirekhak** [comment]
Any updates on this?? I have Same problem

**Comment by h0useRus** [comment]
Hi, we faced with same Invalid Token problem, please help with it

**Comment by alr** [comment]
Same problem, any news on this?

**Comment by spatialguy** [comment]
I am using the following workaround:     

```cs
var config = new ApnsConfiguration(eApnsEnvironment, certificatePath, apnsCertPassword);
// This is a temporary solution for this issue:
// https://github.com/Redth/PushSharp/issues/713
config.InternalBatchSize = 1;
```

Which bypases the Apns connection batches and sends notifications one by one.

The problem is caused by the following code in ApnsConnection.cs, line 160. Foreach loop sets all items in the batch failed.
```
       ...
            } catch (Exception ex) {
                Log.Error ("APNS-CLIENT[{0}]: Send Batch Error: Batch ID={1}, Error={2}", id, batchId, ex);
                foreach (var n in toSend)
                    n.CompleteFailed (new ApnsNotificationException (ApnsNotificationErrorStatusCode.ConnectionError, n.Notification, ex));
            }
     ...
```

**Comment by lepertFLA** [comment]
thank you spatialguy for the workaround for now...I do not see there is way to validate a token prior to queuing (example some apple user uninstalled the app etc).  So it would be best if individual ones that failed where send as failed and the rest processed.  We will wait for the next release and use the workaround for now.

**Comment by ShalvaHMO** [comment]
catch (Exception ex) {
                Log.Error ("APNS-CLIENT[{0}]: Send Batch Error: Batch ID={1}, Error={2}", id, batchId, ex);

                #region Temporary CHANGES
                var errorNotificationToSend = new List<CompletableApnsNotification>();
                foreach (var notificationItem in toSend)
                {
                    if (!notificationItem.Notification.IsDeviceRegistrationIdValid())
                    {
                        errorNotificationToSend.Add(notificationItem);
                    }
                    else
                    {
                        notifications.Enqueue(notificationItem);
                    }
                }
                #endregion Temporary CHANGES

                foreach (var n in errorNotificationToSend)
                {
                    n.CompleteFailed(new ApnsNotificationException(ApnsNotificationErrorStatusCode.ConnectionError, n.Notification, ex));
                }

**Comment by jekcom** [comment]
same here

**Comment by hidim** [comment]
Still, there are no updates :(

**Comment by idealz** [comment]
for the time being i am just doing a check on each device before adding it to queue
 var notification = new ApnsNotification
                    {
                        DeviceToken = device.DeviceToken,
                        Payload = JObject.Parse(JsonConvert.SerializeObject(jsonObject))
                    };
                    try
                    {
                        var bytes = notification.ToBytes();
                        if (bytes.Length > 0)
                        {
                            apnsBroker.QueueNotification(notification);
                        }
                    }
                    catch
                    {
                        _appDeviceService.InvalidateToken(device.DeviceToken);
                    }

**Comment by umutbebek** [comment]
Hi guys, it is true that if some notifications fail on your queue; others will not be send. So i did a little workaround to bypass it. My code sends more than thousands notifications in instant. But it is not a good OOP solution :) I simply start a lot of brokers and send notifications one by one. Because brokers uses their own threads they will run parallel and send all notifications together (of course not in real time but you get the idea ;) ).



`
public class PushNotificationHelper
        {
        private static readonly Lazy<PushNotificationHelper> Manager = 
            new Lazy<PushNotificationHelper>(() => new PushNotificationHelper());

        public static PushNotificationHelper Instance => Manager.Value;

        private int _apnsServiceBrokerCount = 1000;
        private int _apnsServiceBrokerCountQueue = 0; //will be used to add notifications to list!!!!
        private List<ApnsServiceBroker> _apnsBrokers = new List<ApnsServiceBroker>();
        private GcmServiceBroker _gcmBroker;

        PushNotificationHelper()
        {
            StartApns();
            StartGcm();
        }

        ~PushNotificationHelper()
        {
            foreach (var apnsBroker in _apnsBrokers)
            {
                apnsBroker.Stop();
            }
            _gcmBroker.Stop();
        }`



So here i have a lazy singleton helper, and you can see i will start 1000 broker apns :) And the StartApns() code is like:




`
        void StartApns()
        {
            try
            {
                // Configuration (NOTE: .pfx can also be used here)
                ApnsConfiguration config;
               config = new ApnsConfiguration(ApnsConfiguration.ApnsServerEnvironment.Production,"your p12 certificate file path","your p12 password");
               config.InternalBatchSize = 1;
               for (int i = 0; i < _apnsServiceBrokerCount; i++)
                {
                    // Create a new broker
                    var apnsBroker = new ApnsServiceBroker(config);

                    // you can register to events like OnNotificationFailed here!!
                    //apnsBroker.OnNotificationFailed += bla bla
                    
                    // Start the broker
                    apnsBroker.Start();

                    //add to list
                    _apnsBrokers.Add(apnsBroker);
                }
            }
            catch (Exception ex)
            {
                //log error etc.
            }
        }`




config.InternalBatchSize = 1; is important here! Because it programs broker to send notifications one by one.

And you can send the (queue) notifications like this:



`
public void Send(YourMessageDtoClass dto)
{
                //add to next broker
                _apnsBrokers[_apnsServiceBrokerCountQueue].QueueNotification(new ApnsNotification
                {
                    DeviceToken = dto.Token, //your device token,
                    Payload = dto.Payload //your json payload
                });

                //increase queue but do not exceed the broker limit
                _apnsServiceBrokerCountQueue++;
                if (_apnsServiceBrokerCountQueue >= _apnsServiceBrokerCount)
                {
                    _apnsServiceBrokerCountQueue = 0; //!!!!!!!!!!!
                }
}`


And just say in your code:    PushNotificationHelper.Send(......);
Hope everything goes smooth on your side.

**Comment by AndrewFahlgren** [comment]
I made a pull request to fix this issue. If you are still experiencing this issue you can try my code to fix it.

pull request: #877

**Comment by kalpesh-jariwala** [comment]
If I send a batch of notifications and one of the DeviceToken are wrong the correct ones dont sends. . I am using demo code of push sharp for batch of notifications. example,  I am send 100 device tokens and there is in the list first and last are correct. so i am getting only first pushnotification  and last(100) not getting.  Please let me know what was the solution of this problem.

**Comment by AndrewFahlgren** [comment]
@kalpesh-jariwala https://github.com/Redth/PushSharp/pull/885 was created to solve this issue. I am not sure why it hasn't been merged but you could download or fork https://github.com/chillNZ/PushSharp and build it yourself
