### ISSUE TITLE
Is there an ETA for PushSharp that works with .netcore RTM?

### ISSUE THREAD

**Issue by johnkwaters** [Redth/PushSharp#730]

**Comment by developer82** [comment]
+1

**Comment by prabhakarreddy1234** [comment]
I am using .Net Core 1.0.0-preview2-003121.   I cannot install the package  PushSharp v4.0.10 . It says  The dependency PushSharp 4.0.10 does not support framework .Net CoreApp.Version - v1.0 .

Am i missing anything ?

**Comment by developer82** [comment]
What I did is download PushSharp code, I ran the microsoft convert analyze tool on it and fixed it so it can run on .NET Core (just apple & google libraries - the rest I didn't really care for). When I'm done testing and will have time I will upload to github.

**Comment by kspearrin** [comment]
Any update on this @Redth ? This is holding me back from using .NET Core myself since my project has a dependency on this library.

https://docs.microsoft.com/en-us/dotnet/articles/core/porting/libraries

**Comment by developer82** [comment]
@kspearrin Look at my comment above - you can easily migrate - but you will have to maintain it yourself (code updates) until it's officially supported.

**Comment by h3smith** [comment]
@developer82 did you ever upload your branch to github?

**Comment by kspearrin** [comment]
Still waiting for this. Any update?

**Comment by svalagorn** [comment]
I'm using this in the meantime https://www.janaks.com.np/sending-push-notification-ios-asp-net-mvc-core/

**Comment by kspearrin** [comment]
NET Standard 2.0 is due to release soon (maybe March?). I ran a compatibility test on this lib with the [API Port tool](https://github.com/Microsoft/dotnet-apiport) and it shows 100% compatibility with NET Standard 2.0. Should be a simple upgrade then.

**Comment by Redth** [comment]
Yep once 2.0 netstandard hits this will be made to target it.

**Comment by dasMulli** [comment]
A .NET Core 2.0 app should even be able to consume the published package directly through its implicit nugget asset fallback to 4.6.1. Haven't tested it yet though.

**Comment by hscanlan** [comment]
Is there an update for this? I'm looking to integrate into .NET CORE

**Comment by chikien276** [comment]
.NET Standard 2.0 is final. Any update about support .NET core ?

**Comment by tro-solo** [comment]
.NET Standard support would be very much appreciated.

**Comment by delort** [comment]
Any update?

**Comment by bolanki** [comment]
Update... any?

**Comment by juan-arias** [comment]
Seems to be working correctly with .Net Core 2.0: https://github.com/Redth/PushSharp/issues/776#issuecomment-323709554

**Comment by tpetrina** [comment]
It works on Windows, but it doesn't work on Mac.

**Comment by yoambulante** [comment]
I've been using PushSharp for a while on Ubuntu, it was working fine till today.. had a terrible very unfortunate crash, it killed the entire daemon :(

Sep 21 18:00:02 ip-172-30-0-90 dotnet[18832]:    at PushSharp.Apple.ApnsConnection.SendBatch()
Sep 21 18:00:02 ip-172-30-0-90 dotnet[18832]: Unhandled Exception: System.NullReferenceException: Object reference not set
Sep 21 18:00:02 ip-172-30-0-90 dotnet[18832]:    at PushSharp.Apple.ApnsConnection.SendBatch()
Sep 21 18:00:02 ip-172-30-0-90 dotnet[18832]:    at PushSharp.Apple.ApnsConnection.<.ctor>b__1_0(Object state)
Sep 21 18:00:02 ip-172-30-0-90 dotnet[18832]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executi
Sep 21 18:00:02 ip-172-30-0-90 dotnet[18832]: --- End of stack trace from previous location where exception was thrown ---
Sep 21 18:00:02 ip-172-30-0-90 dotnet[18832]:    at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by PleasantD** [comment]
Any news on this? .NET Standard 2.0 is out and we are trying to migrate our framework to it, so support would be welcome.
