### ISSUE TITLE
Unhandled IOException related to Apple FeedbackService

### ISSUE THREAD

**Issue by lazytom** [Redth/PushSharp#732]
We recently upgraded to PushSharp 4.x (using the 4.0.10 Nuget packages) and have experienced this issue twice so far. I don't have any specific steps to reproduce. We use Push Sharp in a WindowsService and when this happens, it kills the service.

Application: XXXService.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
Stack:
   at System.Net.Security._SslStream.ProcessRead(Byte[], Int32, Int32, System.Net.AsyncProtocolRequest)
   at System.Net.Security.SslStream.Read(Byte[], Int32, Int32)
   at PushSharp.Apple.FeedbackService.Check()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

**Comment by lazytom** [comment]
I guess for now I will just wrap the call to `fbs.Check` in a `try ... catch`.
