### ISSUE TITLE
Push Sharp Apple notifications not working with https

### ISSUE THREAD

**Issue by gopikrishnas** [Redth/PushSharp#767]
Recently we have updated PushSharp verson from 2.2.1 to 4.0.1 and used the new code. The code is working with http servers (development machine), but not with https(staging machine).

My code is as follows

#region Apple Notfications Setup
            ApnsConfiguration apnsConfig = null;
            if (ConfigurationManager.AppSettings["IsProduction"].ToString().Trim().ToLower() == "false")
            {
                var appleCert = File.ReadAllBytes(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "AppleDeveloperCertificate.p12"));
                apnsConfig = new ApnsConfiguration(ApnsConfiguration.ApnsServerEnvironment.Sandbox, appleCert, "password");
            }
            else
            {
                var appleCert = File.ReadAllBytes(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "AppleProductionCertificate.p12"));
                apnsConfig = new ApnsConfiguration(ApnsConfiguration.ApnsServerEnvironment.Production, appleCert, "password");
            }

            var apnsBroker = new ApnsServiceBroker(apnsConfig);
            apnsBroker.OnNotificationFailed += (notification, aggregateEx) =>
            {
                aggregateEx.Handle(ex =>
                {
                    // See what kind of exception it was to further diagnose
                    if (ex is ApnsNotificationException)
                    {
                        var notificationException = (ApnsNotificationException)ex;

                        // Deal with the failed notification
                        var apnsNotification = notificationException.Notification;
                        var statusCode = notificationException.ErrorStatusCode;

                        Utility.WriteLog("IOS Push Notifications: Apple Notification Failed: ID=" + apnsNotification.Identifier + ", Code=" + statusCode);

                    }
                    else {
                        // Inner exception might hold more useful information like an ApnsConnectionException           
                        Utility.WriteLog("IOS Push Notifications: Apple Notification Failed for some unknown reason : " + ex.InnerException);
                    }

                    // Mark it as handled
                    return true;
                });
            };

            apnsBroker.OnNotificationSucceeded += (notification) =>
            {
                Utility.WriteLog("IOS Push Notifications: Apple Notification Sent!");
            };

            // Start the broker
            apnsBroker.Start();
            #endregion 

 var jobject = JObject.FromObject(new
                            {
                                aps = new
                                {
                                    alert = "Message from MyProduct",
                                    badge = 10,
                                    sound = "iPhone_Tritone.mp3",
                                }
                            });

                            apnsBroker.QueueNotification(new ApnsNotification
                            {
                                DeviceToken = oDrIphone["DeviceToken"].ToString().Trim(),
                                Payload = jobject
                            });

**I am getting the following error**

IOS Push Notifications: Apple Notification Failed: ID=System.AggregateException: One or more errors occurred. ---> PushSharp.Apple.ApnsNotificationException: Apns notification error: 'ConnectionError' ---> PushSharp.Apple.ApnsConnectionException: SSL Stream Failed to Authenticate as Client ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The message received was unexpected or badly formatted
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at PushSharp.Apple.ApnsConnection.<connect>d__25.MoveNext()
   --- End of inner exception stack trace ---
   at PushSharp.Apple.ApnsConnection.<connect>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PushSharp.Apple.ApnsConnection.<SendBatch>d__21.MoveNext()
   --- End of inner exception stack trace ---
   at PushSharp.Apple.ApnsServiceConnection.<Send>d__2.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) PushSharp.Apple.ApnsNotificationException: Apns notification error: 'ConnectionError' ---> PushSharp.Apple.ApnsConnectionException: SSL Stream Failed to Authenticate as Client ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The message received was unexpected or badly formatted
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at PushSharp.Apple.ApnsConnection.<connect>d__25.MoveNext()
   --- End of inner exception stack trace ---
   at PushSharp.Apple.ApnsConnection.<connect>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PushSharp.Apple.ApnsConnection.<SendBatch>d__21.MoveNext()
   --- End of inner exception stack trace ---
   at PushSharp.Apple.ApnsServiceConnection.<Send>d__2.MoveNext()<---

**Comment by tomasmcguinness** [comment]
How are you hosting this application?

**Comment by Jose7777** [comment]
I have the same issue.
Most Apple notifications are sent, but some receive this error.
I'm sending the notifications inside a webservice in ASP.Net 4.5

Thanks in advance

**Comment by hugohilario** [comment]
I'm facing exactly  the same issue.

**Comment by stefanofalasca** [comment]
same problem me too

**Comment by jvmaval** [comment]
Same here.

**Comment by nmdias** [comment]
Was anyone able to figure this out? I'm having the exact same issue.

**Comment by hugohilario** [comment]
Regenerating another certificate solved the problem to me.

**Comment by tomasmcguinness** [comment]
Problems with certificates can occur when running in a hosted environment such as Azure. If running in an Azure App Service for example, the Service must be set to Basic or above. Free and Shared hosting plans pricing plans have restrictions on how certificates work.  I've experienced this before with Apple Certificates and C#.

**Comment by nmdias** [comment]
Thank you @hugohilario  and @tomasmcguinness 

Regenerating the certificate also solved it for me.

**Comment by sercanparker** [comment]
Everybody claims that when we regenerate out .p12 or .pfx file, it is going to be solved. Yes I solved with it, However I faced that problem with file which are generated yesterday and today I got this error message. Should I regenerate all the time it every day or every week ? By the way, I got it on localhost too before regeneration.

**Comment by nmdias** [comment]
Test these ports on your server :

```
const string APNS_SANDBOX_HOST = "gateway.sandbox.push.apple.com";
const string APNS_PRODUCTION_HOST = "gateway.push.apple.com";

const string APNS_SANDBOX_FEEDBACK_HOST = "feedback.sandbox.push.apple.com";
const string APNS_PRODUCTION_FEEDBACK_HOST = "feedback.push.apple.com";

const int APNS_SANDBOX_PORT = 2195;
const int APNS_PRODUCTION_PORT = 2195;

const int APNS_SANDBOX_FEEDBACK_PORT = 2196;
const int APNS_PRODUCTION_FEEDBACK_PORT = 2196;
```

Also test 443. Try to open them explicitly.

..I made the mistake of assuming my production server was connecting because it worked previously, only to find out something as simple as a closed port was preventing me from pushing notifications. 

Best of luck.

**Comment by Cemoo** [comment]
> @nmdias Regenerating another certificate solved the problem to me.

Hi

Did you get same issue again? Because we had same problem too

**Comment by badpaybad** [comment]
I found this line:   
    stream.AuthenticateAsClient(Configuration.Host, certificates, System.Security.Authentication.SslProtocols.Tls, false);

Replace by this:
    stream.AuthenticateAsClient(Configuration.Host, certificates, System.Security.Authentication.SslProtocols.Tls12, false);
