### ISSUE TITLE
Apn "Connection Error"

### ISSUE THREAD

**Issue by liormenashe** [Redth/PushSharp#795]
### What version of PushSharp are you using?
4.0.10
### Describe your issue:
I'm using PushSharp 4.0.10, installed from NuGet

In the OnNotificationFailed(ApnsNotification, AggregateException) event of the Apns broker, I often get 'ConnectionError' exception:

After getting this error all the other pushes will get the same error.

Does someone know why it's happening and how to fix this?

Thanks,
Lior

**Comment by SiddiquiImran** [comment]
I am also getting the same issue for iOS.

**Comment by liormenashe** [comment]
I can see that it happens when i'm trying to send by mistake a push notification
to apple using google token.

But still, how can it be fixed that it won't crash in this cases?

**Comment by SiddiquiImran** [comment]
this is my log:



Apple Notification Failed: DeviceToken=3e77e5ba33c0a45f4a4f71c7dd5aedf89184f463f00d3b6e35293c9196dc4e94,Payload={
  "aps": {
    "alert": {
      "body": "Test! Bitte kurze Whatsapp an mich, wenn angekommen ;) Gruß CR",
      "title": "GB 1976"
    }
  },
  "ModuleId": null,
  "ActivationId": 0,
  "image": "icon",
  "notId": 727395098
},
Code=ConnectionError,
 IsDeviceRegistrationIdValid = True, 
exception: 
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 17.188.142.148:2195
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PushSharp.Apple.ApnsConnection.<connect>d__25.MoveNext()

**Comment by SiddiquiImran** [comment]
I found one think i am not getting this error if i am sending notification to only one device.

But if i try to send notification to more the one device using foreach like:
 foreach (var deviceToken in MY_REGISTRATION_IDS)
            {
                SendiOSMsg(deviceToken);
            }

I am getting this error.

any help ? :(

**Comment by SiddiquiImran** [comment]
We have spent around 2 days on it and found that as our sever is over VPN we have to make some changes on firewall level, link for the same:

https://support.apple.com/en-us/HT203609
https://www.ca.com/us/services-support/ca-support/ca-support-online/knowledge-base-articles.tec602117.html

**Comment by sultanwork77** [comment]
I am still facing same issue. When i pass device tokens its able to send notifications and if i send kind of broadcast message then if one failed with connection error then all are failing. Any method or way to check if the token is valid before queuing. Please suggest.
