### ISSUE TITLE
AuthenticateAsClientAsync - An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by tweek82** [Redth/PushSharp#820]
### What version of PushSharp are you using?
Latest 4.0.10

### Describe your issue:
Since wednesday night, april 19th, we regularly receive this error:
`System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host`

The behaviour we experience is that the connection 'hangs' at this point. Example from logging:

```
13:11:33 | PushServiceV2 | APNS-Client[7]: Sending Batch ID=1, Count=21
13:11:33 | PushServiceV2 | APNS-Client[7]: Connecting (Batch ID=1)
13:11:33 | PushServiceV2 | APNS-Client[7]: client.ConnectAsync
13:11:33 | PushServiceV2 | APNS-Client[7]: client.Client.SetSocketOption
13:11:33 | PushServiceV2 | APNS-Client[7]: SetSocketKeepAliveValues
13:11:33 | PushServiceV2 | APNS-Client[7]: Configuration.SkipSsl:False
13:11:33 | PushServiceV2 | APNS-Client[7]: Create our ssl stream
13:11:33 | PushServiceV2 | APNS-Client[7]: stream.AuthenticateAsClient
13:32:03 | PushServiceV2 | APNS-CLIENT[7]: Send Batch Error: Batch ID=1, Error=System.IO.IOException:
```
As you can see, it takes 21 minutes before this exception is thrown. 

This happens on this line in APNSConnection.cs:

```
try {
    stream.AuthenticateAsClient(Configuration.Host, certificates, System.Security.Authentication.SslProtocols.Tls12, false);
} catch (System.Security.Authentication.AuthenticationException ex) {
    throw new ApnsConnectionException ("SSL Stream Failed to Authenticate as Client", ex);
}
```
90% of the APNS push notifications are successfully sent. So I can confirm that the SSL certificate is good.

Anyone has a clue what the issue could be? I've set my own interval between the batches to 5 minutes, so I won't expect this hang to be caused by a preventive DDOS Apple action.

Stacktrace from logging:
```
13:32:03 | PushServiceV2 | APNS-CLIENT[7]: Send Batch Error: Batch ID=1, Error=System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at PushSharp.Apple.ApnsConnection.<connect>d__25.MoveNext() in c:\Workspaces\PushServices\PushService\PushSharp.Apple\ApnsConnection.cs:line 365
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PushSharp.Apple.ApnsConnection.<SendBatch>d__21.MoveNext() in c:\Workspaces\PushServices\PushService\PushSharp.Apple\ApnsConnection.cs:line 143
13:32:03 | PushServiceV2 | APNS-Client[7]: Sent Batch, waiting for possible response...
13:32:03 | PushServiceV2 | APNS-Client[7]: Reader Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PushSharp.Apple.ApnsConnection.<Reader>d__23.MoveNext() in c:\Workspaces\PushServices\PushService\PushSharp.Apple\ApnsConnection.cs:line 209
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PushSharp.Apple.ApnsConnection.<SendBatch>d__21.MoveNext() in c:\Workspaces\PushServices\PushService\PushSharp.Apple\ApnsConnection.cs:line 169

```

Many thanks in advance.

**Comment by tweek82** [comment]
The problem and solution to this problem:
[http://stackoverflow.com/a/43732436/167196](url)

**Comment by nithyanantham** [comment]
@tweek82 Stackoverflow link was removed. Can you please post the solution here.

**Comment by sonergonul** [comment]
@nithyanantham 

The link goes to https://github.com/Redth/PushSharp/issues/url but you can always "copy as a text" this url.

Here is the full answer by the way;

> I think we just hit a limit on number of connections. I have read this document: [Troubleshooting Push Notifications](https://developer.apple.com/library/content/technotes/tn2265/_index.html) and took note of this line:
> 
> Another possibility is that you've connected too many times to APNs and further connections have been temporarily blocked. As is documented in the Local and Remote Notification Programming Guide, developers are expected to open a connection and leave it open. If a connection is opened and closed repeatedly, APNs will treat it as a denial of service attack and **block connections for a period of time**.
> 
> I rewrote my implementation and the usage of PushSharp so that TCP connections are created and closed as little times as possible. It's running for a few days now without any problems. In the logging I see that the connection is only disconnected once each day by apple, and PushSharp nicely reconnects.
