### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by faisalcse** [Redth/PushSharp#837]
I am getting frequently connection error while sending Push to iOS.

"Failed to Connect, check your firewall settings!

   at PushSharp.Apple.ApnsConnection.<connect>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PushSharp.Apple.ApnsConnection.<SendBatch>d__21.MoveNext()
"

Please advice.

**Comment by earamsey** [comment]
I am having the same issue any help here?

**Comment by koustubh** [comment]
I am facing same error message when I used sandbox host with dev certificat..any help?

**Comment by sercanparker** [comment]
Is there any advice or solution @koustubh @earamsey @faisalcse ? I could not understand that it's about APN side or library side.
