### ISSUE TITLE
Unhandled Exceptions in ApnsConnection

### ISSUE THREAD

**Issue by roeaharoni365** [Redth/PushSharp#853]
### What version of PushSharp are you using?
4.0.10.0

### Describe your issue:
in the process running Pushsharp we have logging for unhandled exceptions
Code Snippet
`AppDomain.CurrentDomain.UnhandledException += CurrentDomainOnUnhandledException;

 private static void CurrentDomainOnUnhandledException(object sender, UnhandledExceptionEventArgs unhandledExceptionEventArgs)
        {
            string message = string.Format("unhandled Exception caught. ex: {0}", unhandledExceptionEventArgs.ExceptionObject);
            Logging.Log(ELogCategory.Exception, message);
        }
`
In this Log we've seen a few of these exceptions, after sending a batch of ~200K+ notifications:
**_System.NullReferenceException: Object reference not set to an instance of an object.
   at PushSharp.Apple.ApnsConnection.<SendBatch>d__21.MoveNext()_** (full stack trace pasted below)

### What are the steps required to reproduce this issue?
Unfortunately, it isn't reproduced consistently but happens from time to time

### Please provide any Exception Stack Traces
_**System.NullReferenceException: Object reference not set to an instance of an object.
   at PushSharp.Apple.ApnsConnection.<SendBatch>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PushSharp.Apple.ApnsConnection.<<-ctor>b__1_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__5(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()**_

**Comment by roeaharoni365** [comment]
after reading through the issues here I've seen that many people have encountered this issue
it happens in APNSConnection, line 163
whithin the catch  of sending the batch of notifications in this line:
`  ** foreach (var n in toSend)
                    n.CompleteFailed (new ApnsNotificationException (ApnsNotificationErrorStatusCode.ConnectionError, n.Notification, ex));**`


there are a few potential null references in this line (toSend itself, n)
and getting this exception within a catch block is quite risky

I've added a try catch block and null checks for this and it seems to solve the issue

```
if (toSend != null)
                {
                    foreach (var n in toSend)
                    {
                        try
                        {
                            if (n != null)
                            {
                                n.CompleteFailed(
                                    new ApnsNotificationException(ApnsNotificationErrorStatusCode.ConnectionError,
                                        n?.Notification, ex));
                            }
                        }
                        catch (Exception e)
                        {
                            Log.Error("APNS-CLIENT[{0}]: bad notification handled in", id, batchId, e);
                        }

                    }
                }
```
