### ISSUE TITLE
PushSharp.Apple.ApnsConnectionException: SSL Stream Failed to Authenticate as Client

### ISSUE THREAD

**Issue by raheem52** [Redth/PushSharp#895]
I am using PushSharp 4.0.10

When I am trying to send iOS notification.
 
I receive below error

Send Batch Error: Batch ID=1, Error=PushSharp.Apple.ApnsConnectionException: SSL Stream Failed to Authenticate as Client ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Interop+AppleCrypto+SslException: bad protocol version8
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at PushSharp.Apple.ApnsConnection.connect()
   --- End of inner exception stack trace ---
   at PushSharp.Apple.ApnsConnection.connect()
   at PushSharp.Apple.ApnsConnection.SendBatch()

**Comment by dannycabrera** [comment]
@raheem52 seeing same this morning too. Had some push notifications go out but occasionally getting this exception.

**Comment by MostafaSholkany** [comment]
Same error withe me

**Comment by Sebastian506563** [comment]
Same here, 
1. Tested only locally
2. Started to fail after update to Windows 10.
3. First notification after running always fails, next are fine.
I am guessing something wrong with Tls1.0

**Comment by sevafeld** [comment]
Same here

**Comment by dannycabrera** [comment]
Just updated my code to force TLS 1.2 and waiting to see if this error shows up again.

`System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;`

**Comment by dannycabrera** [comment]
No errors in about 4 hours so this might have done the trick. Thanks @Sebastian506563 for pointing out TLS issue.

**Comment by jlubeck** [comment]
@dannycabrera where did you put that? I'm having the same issue, just put that line before `apnsBroker.Start()` and it's still failing for me...

**Comment by sonergonul** [comment]
> @dannycabrera where did you put that? I'm having the same issue, just put that line before `apnsBroker.Start()` and it's still failing for me...

Usually this should put in your `Application_Start` method but this depends on your architecture of course.

**Comment by dannycabrera** [comment]
Thanks @sonergonul. Exactly where I placed it, right before any PushSharp initializing.

**Comment by jlubeck** [comment]
Doing just that didn't fix it for me. I had to run this on the recommended settings to fix the Ciphers on my computer as well: https://www.nartac.com/Products/IISCrypto

**Comment by dannycabrera** [comment]
@jlubeck curious, what OS are you running PushSharp on?

**Comment by jlubeck** [comment]
@dannycabrera  Windows Server 2012

**Comment by danhudsonfortyau** [comment]
Is there a chance anyone will update the nuget package to include the TLS fix?

**Comment by harvey-green** [comment]
I had this same issue, so checked out the master branch and built the project locally. Then included the references to the required DLLs (Apple and Core) manually into my project. The NuGet package for PushSharp is 3 years old and so does not include the required fixes for TLS 1.2.

**Comment by harvey-green** [comment]
By the way I was doing sandbox Apple VoIP push notifications via

gateway.sandbox.push.apple.com - port 2195

feedback.sandbox.push.apple.com - port 2196

They started failing on 23 July. Prior to that they were working fine with the NuGet package.

**Comment by xilibro** [comment]
oh my god, it has taking my two days.

**Comment by xilibro** [comment]
> I had this same issue, so checked out the master branch and built the project locally. Then included the references to the required DLLs (Apple and Core) manually into my project. The NuGet package for PushSharp is 3 years old and so does not include the required fixes for TLS 1.2.

love you so much

**Comment by danhudsonfortyau** [comment]
The last two links are references to the updated PushSharp nuget. I'm not sure if the original author is trying to monentize PushSharp or if its a branch of someone else's. I ran the nuget packages and got past the current set of Tls errors related to Apple updates. Hope this helps folks.

https://nugetmusthaves.com/Package/LogicSoftware.PushSharp 
https://nugetmusthaves.com/Package/LogicSoftware.PushSharp
https://nugetmusthaves.com/Package/PushSharp.NetCore2.1
