### ISSUE TITLE
 Apns notification error: 'ConnectionError' -  System.NullReferenceException

### ISSUE THREAD

**Issue by elvirp** [Redth/PushSharp#902]
What version of PushSharp are you using?
We are using PushSharp.Apple 1.0.1

Describe your issue:
We get the following error:

Source : PushSharp.Apple
Exception : 
PushSharp.Apple.ApnsNotificationException: Apns notification error: 'ConnectionError' ---> System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object.
   à PushSharp.Apple.ApnsConnection.createBatch(List`1 toSend)
   à PushSharp.Apple.ApnsConnection.<SendBatch>d__21.MoveNext()
--- End of inner exception stack trace ---
   à PushSharp.Apple.ApnsServiceConnection.<Send>d__2.MoveNext()

What are the steps required to reproduce this issue?
It seems to happen randomly. I'm using PushSharp

### Please provide any Exception Stack Traces

lease advise how to troubleshoot this error.

**Comment by Gedonist** [comment]
We have same issue:

`Application: Push.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at PushSharp.Apple.ApnsConnection+<SendBatch>d__21.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at PushSharp.Apple.ApnsConnection+<<-ctor>b__1_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()`
